### ISSUE TITLE
Crashing when trying to visualize buildings

### ISSUE THREAD

**Issue by EmmaRavens** [baileyholl/blockprints-mod#15]
Crashed when trying to visualize the following builds

Build 1 (Polonium Factory) -> https://blockprints.io/schematic/ac7a437f-e411-40d2-8a04-9e5fae144e23
Crash Report -> [crash-2024-08-19_15.59.39-client.txt](https://github.com/user-attachments/files/16662014/crash-2024-08-19_15.59.39-client.txt)

Build 2 (Simple Blacksmith) -> https://blockprints.io/schematic/e6ed5e8d-ba94-4f12-85d3-8f0e09ed910a
Crash Report -> [crash-2024-08-19_15.50.17-client.txt](https://github.com/user-attachments/files/16662016/crash-2024-08-19_15.50.17-client.txt)

**Comment by Jarva** [comment]
Is this still happening on 1.21.1-2.0.1? Fluid rendering should be fixed

**Comment by EmmaRavens** [comment]
No, seems to be fixed, thank you
