### ISSUE TITLE
Mediakeys on keyboard (change track, pause etc.), always opens the blockprints gui even if the keybind for it is unbounded.

### ISSUE THREAD

**Issue by Gbergz** [baileyholl/blockprints-mod#17]
Issue: Mediakeys on keyboard (if present on it) (change track, pause etc.), always opens the blockprints gui even if the keybind for it is unbounded.

Version: v2.0.1

**Comment by Jarva** [comment]
I'm not able to reproduce this, my media keys don't even trigger the key event in Minecraft, what OS are you running?

Do you have any special keyboard software?

**Comment by Gbergz** [comment]
Windows 11.
No special keyboard software installed.
Keyboard is a: HyperX Alloy Elite 2

**Comment by Gbergz** [comment]
Hopped on an instance with just the mod & NeoForge v21.1.37 and it's the same. 
Tested incase it was a mod conflict in the modpack.

**Comment by Jarva** [comment]
I can't reproduce on Linux, maybe @baileyholl is able to replicate?

**Comment by baileyholl** [comment]
I could not reproduce it myself, but I did find a bug where the key wasn't checked for being unbound. Let me know if 2.0.2 fixes it.

**Comment by Gbergz** [comment]
That fixed it.

Thanks!
